# NumPy Practice Problems

In [3]:
#Importing numpy package
import numpy as np

TASK 1 :
Create a null vector of size 10 but the fifth value which is 1.

In [28]:
arr = np.zeros(10,dtype=int)
print("Original array: ",arr)

arr[4] = 1
print("Updated array:  ",arr)

Original array:  [0 0 0 0 0 0 0 0 0 0]
Updated array:   [0 0 0 0 1 0 0 0 0 0]


TASK 2: Create a vector with values ranging from 10 to 49.

In [33]:
np.arange(start=10,stop=50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

TASK 3: Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.random.randint(low=0,high=8,size=(3,3))

array([[7, 6, 1],
       [1, 3, 4],
       [0, 2, 6]])

TASK 4: Find indices of non-zero elements from [1,2,0,0,4,0]

In [35]:
arr = np.array([1,2,0,0,4,0])
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

TASK 5: Create a 10x10 array with random values and find the minimum and maximum values.

In [14]:
arr = np.random.randn(10,10)
print(arr)
print("\n")

min = arr.min()
print(min)
print("\n")

max = arr.max()
print(max)

[[-6.48777895e-01  1.03014599e+00 -1.41003257e+00 -1.43406345e-01
  -8.22412684e-01 -4.40287672e-01  1.59890303e+00  1.98809577e-01
   1.39824123e+00  2.53247147e-01]
 [-1.23669346e+00  1.09281458e+00 -2.58984752e+00  2.15736924e-01
  -1.35256702e+00 -1.34853869e+00  1.18628674e+00  6.46215608e-01
   4.52091312e-01  6.84089198e-01]
 [ 7.14796173e-01 -5.33116340e-02 -1.53657931e+00 -9.69585255e-01
  -1.16588171e+00 -3.56153868e-01 -1.01770608e+00  1.54792733e+00
   1.03440594e+00  9.67840818e-01]
 [ 6.85487470e-01 -6.83392646e-01  1.94556058e-01  7.06590688e-01
   1.35477808e+00 -2.50472373e-01 -1.65895733e+00  1.16593531e+00
   6.70192590e-01  4.57293518e-01]
 [ 2.89421757e+00 -1.16409764e+00  9.15112951e-02 -1.12196555e+00
  -1.85872087e+00  8.70099210e-01  8.13972123e-02 -4.52020271e-01
   2.46308125e-02 -9.23194406e-01]
 [ 1.11723563e+00  1.07470650e+00  4.68042627e-01 -7.97441326e-01
  -8.26147881e-02 -3.28852592e-01  9.05018564e-02 -1.41945856e+00
  -1.43727240e+00  3.40491433e-01

TASK 6: Create a random vector of size 30 and find the mean value.

In [32]:
arr = np.random.rand(30)
print(arr)
print("\n")

mean = np.mean(arr)
print("Mean of array is:",mean)

[0.46042534 0.1935763  0.49719081 0.13620169 0.60512925 0.51322728
 0.87039879 0.45019384 0.78469015 0.26114063 0.24071867 0.24478186
 0.28381347 0.86388298 0.79149858 0.80926096 0.02974528 0.05145182
 0.25426492 0.89424986 0.73388786 0.31617652 0.83448689 0.51305323
 0.52958814 0.65332688 0.03649002 0.5413209  0.30201807 0.91063546]


Mean of array is: 0.4868942144724182
